# Generated by Django 5.2.4 on 2025-07-13 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recertificationdocument_delete_recertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='area_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('COMMON_AREA', 'Common Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
